version: "2.8.0"
name: Benotes
slug: benotes
description: "Notes & Bookmarks - Save all your information in one place"
arch:
  - armv7
  - amd64
map:
  - config:rw
  - share:rw
ports:
  80/tcp: 8000
options:
  "APP_NAME": "Benotes"
  "APP_ENV": "production"
  "APP_DEBUG": 0
  "APP_URL": "http://localhost"
  "APP_TIMEZONE": "UTC"

  "APP_KEY": ""
  "JWT_SECRET": ""

  "DB_CONNECTION": "sqlite"
  "DB_HOST": ""
  "DB_PORT": ""
  "DB_DATABASE": "/var/www/storage/database.sqlite"
  "DB_USERNAME": ""
  "DB_PASSWORD": ""



  "GENERATE_MISSING_THUMBNAILS": "true"
  "USE_FILESYSTEM": "true"
  "CACHE_DRIVER": "file"

  "MAIL_DRIVER": "smtp"
  "MAIL_PORT": "587"
  "MAIL_USERNAME": "benotes@example.com"
  "MAIL_PASSWORD": "exampletochange"
  "MAIL_ENCRYPTION": "tls"
  "MAIL_HOST": "smtp.example.com"
  "MAIL_FROM_ADDRESS": "noreplay@example.com"
  "MAIL_FROM_NAME": "Benotes"
schema:
  "APP_NAME": "str?"
  "APP_ENV": "str?"
  "APP_DEBUG": "bool"
  "APP_URL": "str"
  "APP_TIMEZONE": "str"
  "APP_KEY": "password?"
  "JWT_SECRET": "password?"

  "DB_CONNECTION": "str"
  "DB_HOST": "str?"
  "DB_PORT": "str?"
  "DB_DATABASE": "str"
  "DB_USERNAME": "str?"
  "DB_PASSWORD": "password?"

  "GENERATE_MISSING_THUMBNAILS": "bool"
  "USE_FILESYSTEM": "bool"
  "CACHE_DRIVER": "str"

  "MAIL_DRIVER": "str?"
  "MAIL_PORT": "int?"
  "MAIL_USERNAME": "str?"
  "MAIL_PASSWORD": "password?"
  "MAIL_ENCRYPTION": "str?"
  "MAIL_HOST": "str?"
  "MAIL_FROM_ADDRESS": "str?"
  "MAIL_FROM_NAME": "str?"