name: Sharry
version: "1.12.1"
slug: sharry
description: Simple File Sharing Service.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  9090/tcp: 9090
  