version: "0.0.1"
name: Databag
slug: databag-1
description: Databag is a selfhosted messaging service.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  7000/tcp: 7000
data_location: /config/addons_config/databag
environment:
  "ADMIN": str?
