version: "0.1.6"
name: Databag
slug: databag
description: Databag is a selfhosted messaging service.
arch:
  - armv7
  - amd64
map:
  config: rw
ports:
  7000/tcp: 7000
data_location: /config/addons_config/databag
options:
  "ADMIN": Admin
schema:
  "ADMIN": password