version: "latest"
image: balzack/databag
name: Databag
slug: databag
description: Databag is a selfhosted messaging service.
arch:
  - arm64
  - amd64
ports:
  7000/tcp: 7000
data_location: /config/addons_config/databag
environment:
  "ADMIN": str?
