version: "0.1.7"
name: Databag
slug: databag
description: Databag is a selfhosted messaging service.
arch:
  - armv7
  - amd64
map:
  - config:rw
  - share:rw
ports:
  7000/tcp: 7000
options:
  "ADMIN": changeme
schema:
  "ADMIN": password