version: "2.1.1"
name: Dashy
slug: dashy
description: Dashy helps you organize your self-hosted services by making them accessible from a single place
arch:
  - armv7
  - amd64
map:
  - config:rw
ports:
  4000/tcp: 4000